### ISSUE TITLE
Latest added file stuck in infinite buffer when using Infuse with Jellyfin

### ISSUE THREAD

**Issue by WLines84** [skjaere/DebriDav#34]
I have setup Debridav with docker compose and it works flawlessly 90% of time, however it seems that the most recent files it has added get stuck in an infinite buffer when I'm using Infuse through Jellyfin.
Example if I try to watch episode 1 I can see it perfectly, when I move to episode 2 I see like 5-10second and I get buffering screen and never moves on.

Logs seem ok on the debridav container, and I'm not even sure how to troubleshoot this.
If I mount real-debris webdav directly in infuse it works without any problems. 

current config:
```
  debridav:
    image: ghcr.io/skjaere/debridav:v0
    container_name: debridav
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DEBRIDAV_ROOTPATH=${DEBRIDAV_ROOT_PATH}
      - DEBRIDAV_DOWNLOADPATH=${DEBRIDAV_DOWNLOAD_PATH}
      - DEBRIDAV_MOUNTPATH=${DEBRIDAV_MOUNT_PATH_CONTAINERS}
      - DEBRIDAV_DEBRIDCLIENTS=${DEBRIDAV_DEBRID_CLIENTS}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DEBRIDAV_DB_HOST}:${DEBRIDAV_DB_PORT}/${DEBRIDAV_DB_DATABASE_NAME}?user=${DEBRIDAV_DB_USERNAME}&password=${DEBRIDAV_DB_PASSWO>
      - REALDEBRID_APIKEY=${REAL_DEBRID_API_KEY}
      - SONARR_INTEGRATIONENABLED=${SONARR_INTEGRATION_ENABLED}
      - SONARR_HOST=${SONARR_HOST}
      - SONARR_PORT=${SONARR_PORT}
      - SONARR_APIKEY=${SONARR_API_KEY}
      - RADARR_INTEGRATIONENABLED=${RADARR_INTEGRATION_ENABLED}
      - RADARR_HOST=${RADARR_HOST}
      - RADARR_PORT=${RADARR_PORT}
      - RADARR_APIKEY=${RADARR_API_KEY}
      - DEBRIDAV_CHUNKCACHINGSIZETHRESHOLD=0
    ports:
      - ${DEBRIDAV_PORT}:8080
      - "8000:8000"
    networks:
      - debridav-network
    volumes:
      - ${DEBRIDAV_ROOT_HOST_FS}:${DEBRIDAV_ROOT_PATH}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 2s
      start_period: 2s
      retries: 1000
    depends_on:
      postgres-debridav:
        condition: service_healthy


  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
    volumes:
      - ${DEBRIDAV_MOUNT_PATH_HOST_FS}:${DEBRIDAV_MOUNT_PATH_CONTAINERS}:rshared
      - $DOCKERDIR/appdata/rclone/:/config/rclone/
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command: "mount debridav: $DEBRIDAV_MOUNT_PATH_CONTAINERS --uid 1000 --gid 1000 --default-permissions --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode>
    ports:
      - "5572:5572"
    depends_on:
      debridav:
        condition: service_healthy
    networks:
      - debridav-network
```
